keys:
- &procyon age18nk2d5evh26qw43w8lwcp8p9dq4g2mdl0tj0uctsstdwxlnu3pgqkjqz4v
- &pollux age14edghp35n0lsgnrxslg273nm6jfc3rs9qsl7vddd99papjlz6f2s5zqagn
deployers: &deployers
- *procyon
creation_rules:
- path_regex: secrets/deployer/.*
  age: *deployers
- path_regex: secrets/procyon/.*
  age:
  - *procyon
- path_regex: secrets/pollux/.*
  age:
  - *pollux
  - *procyon
