keys:
- &altair age1n9l0amsxty0z4du87u5w96n97h3wpzcc67d7n2enm76ljyhv3q0qaqkf7m
- &procyon age1hfx08t9ngl44vh4qthvkpfrj5cal5m08lcvejr20j4vyrawazf8qt3s2vn
deployers: &deployers
- *altair
creation_rules:
- path_regex: secrets/deployer/.*
  age: *deployers
- path_regex: secrets/procyon/.*
  age:
  - *procyon
