name: Setup Nix with nixbuild.net
description: Configures SSH and installs Nix pointing at nixbuild.net as a remote builder

inputs:
  ssh_key:
    required: true
    description: SSH private key for nixbuild.net

runs:
  using: composite
  steps:
    - name: Setup SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.ssh_key }}
        name: id_ed25519
        known_hosts: "eu.nixbuild.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPIQCZc54poJ8vqawd8TraNryQeJnvH1eLpIDgbiqymM"
        config: |
          Host eu.nixbuild.net
            ServerAliveInterval 60
            IPQoS throughput

    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v34
      with:
        enable_kvm: false
        nix_conf: |
          substituters = https://cache.nixos.org/ ssh://eu.nixbuild.net
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixbuild.net/bob-1:8tJU22/XxyINhP+wM65gwSIlg0rrQrmWhFf5+8u8F/s=
          builders = eu.nixbuild.net x86_64-linux - 100 1 benchmark,big-parallel
          max-jobs = 0
